name: Test Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Wait for cluster to be ready
        run: kubectl wait --for=condition=Ready nodes --all --timeout=120s

      - name: Add Helm stable repo
        run: helm repo add stable https://charts.helm.sh/stable

      - name: Update Helm repos
        run: helm repo update

      - name: Install Helm chart
        run: helm install my-release stable/my-chart --namespace my-namespace --create-namespace

      - name: Test Helm chart installation
        run: kubectl get pods --namespace my-namespace

      - name: Delete Helm release
        run: helm uninstall my-release --namespace my-namespace

      - name: Delete Kind cluster
        run: kind delete cluster --name test-cluster
