name: Test Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.23.0"
          config: ./config/kind-conf.yaml

      - name: Wait for cluster to be ready
        run: kubectl wait --for=condition=Ready nodes --all --timeout=120s

      - name: Setup Ingress
        run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Ingress Wait
        run: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=120s

      - name: Get ingress details
        run: kubectl get all -n ingress-nginx

      - name: Install Helm chart
        run: |
          helm upgrade --install neodash-test ./neodash --wait --atomic --install \
          --set enable_reader_mode=false \
          --set service.type=ClusterIP \
          --set service.port=80 \
          --set ingress.enabled=true \
          --set ingress.className=nginx \
          --set "ingress.hosts[0].host=localhost" \
          --set "ingress.hosts[0].paths[0].path=/" \
          --set "ingress.hosts[0].paths[0].pathType=Prefix"

      - name: Show ingress
        run: kubectl get ingress -o wide

      - name: Test Helm chart installation
        run: kubectl get pods -o wide

      - name: kubectl get all
        run: kubectl get all -o wide

      - name: events
        run: kubectl get events --sort-by='.lastTimestamp'

      - name: Check service
        run: kubectl get svc -o wide

      - name: sleep
        run: sleep 2m

      - name: Show ingress
        run: kubectl get ingress -o wide

      - name: Get logs of ingress controller pod
        run: |
          INGRESS_POD=$(kubectl get pods -n kube-system -l app.kubernetes.io/name=ingress-nginx -o jsonpath='{.items[0].metadata.name}')
          kubectl logs $INGRESS_POD -n kube-system

      - name: Test service URL
        run: curl http://localhost:5005

      - name: Delete Helm release
        run: helm uninstall my-release --namespace my-namespace

      - name: Delete Kind cluster
        run: kind delete cluster --name test-cluster
