name: Test Helm Chart

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.23.0"

      - name: Wait for cluster to be ready
        run: kubectl wait --for=condition=Ready nodes --all --timeout=120s

      - name: Install Helm chart
        run: helm upgrade --install neodash-test ./neodash --set enable_reader_mode=false #--wait --atomic --install

      - name: Test Helm chart installation
        run: kubectl get pods
      - name: kubectl get all
        run: kubectl get all
      - name: events
        run: kubectl get events --sort-by='.lastTimestamp'
      - name: Check service
        run: kubectl get svc

      - name: Test service URL
        run: |
          SERVICE_IP=$(kubectl get svc neodash-test --template "{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}")
          curl -f http://$SERVICE_IP:5005

      - name: Delete Helm release
        run: helm uninstall my-release --namespace my-namespace

      - name: Delete Kind cluster
        run: kind delete cluster --name test-cluster
